### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by BurningBOB** [sskodje/GifImageSource#3]
There are 2 issues and maybe a feature request. The first one causes a hard crash and gives me either "processes is being used by another process" or similar with "access denied"

The second issue only happens in debugging with native code enabled.

The feature request would be an event trigger for when the gif or image finishes loading.

See this video to understand better https://onedrive.live.com/redir?resid=A9B13DE7E292CEE0!1013929&authkey=!AIk36ZAwbISLig8&ithint=video%2cmp4

**Comment by sskodje** [comment]
I have identified your main issue, which is happening if you load several images with the same URI simultaneously. I must fix that by synchronizing access to the cache file. 

As for your second issue, i believe you are just hitting a first chance exception that is usually swallowed in the library. You can turn off pausing on first chance exceptions in the visual studio exception settings. I fixed the offending cast anyway so it won't be seen again.

The third request is already partially in the library. I've not found a way to use attached events directly from xaml like you can in WPF, but there is an "ImageLoaded" event you can use like this:

```
     AnimationBehavior.OnImageLoaded += AnimationBehavior_OnImageLoaded;

    private void AnimationBehavior_OnImageLoaded(object sender, GifImageSource imageSource)
    {
        BusyIndicator.IsActive = false;
    }
```

The sender is the Image control, and the eventargs is the GifImageSource. You will need to handle the rest yourself, getting the DataContext of the Image control for example.

I've stumbled upon a few bugs and memory leaks i have to sort out however, so it's probably going to take a couple days before i upload a new version.

**Comment by BurningBOB** [comment]
Awesome thank you. The OnImageLoaded event seems to work good but does not trigger if the image is not a gif.

**Comment by sskodje** [comment]
> The OnImageLoaded event seems to work good but does not trigger if the image is not a gif. 

Alright i'll add it to the to-do list :)

**Comment by sskodje** [comment]
I uploaded a new version on github and NuGet. On my test app all issues seems to be fixed now, but test it out in your app and let me know.

**Comment by BurningBOB** [comment]
im getting this after the update. http://puu.sh/p5kn7/b773a0550c.png

**Comment by sskodje** [comment]
I had to change the event to accommodate handling non-gifs. Recreate it or change the event arg from GifImageSource to ImageSource, then do a type check yourself.

**Comment by BurningBOB** [comment]
Changing it to ImageSource was the fix. Thanks for all your work.
